#@ load("@ytt:data", "data")

#@ def labels():
simple-demo-another: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: simple-demo-another
spec:
  ports:
    - port: #@ data.values.svc_port
      targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: simple-demo-another
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
        - name: simple-demo-another
          image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
          env:
            - name: HELLO_MSG
              value: #@ data.values.hello_msg
