#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: simple-demo
    path: ../../simple-demo/
    newImage: #@ data.values.registry_location + data.values.push_images_repo
    preresolved: true
    tags: [latest]
    #@ if data.values.base_registry:
    docker:
      build:
        rawOptions: #@ ["--build-arg", "BASE_REGISTRY=" + data.values.base_registry, "--build-arg", "BASE_IMAGE=" + data.values.moa_scheduler_image, "--build-arg", "BASE_TAG=" + data.values.moa_scheduler_tag]
    #@ end
destinations:
  - image: simple-demo
    newImage: #@ data.values.registry_location + data.values.push_images_repo
